---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qba-back-end-config
data:
{{- range $key, $value := .Values.env.qbaBackEnd }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qba-rabbitmq-config
data:
  RABBITMQ_DEFAULT_USER: ranul
  RABBITMQ_DEFAULT_PASS: "ranul@123"