apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qba.fullname" . }}
  labels:
    {{- include "qba.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  #These are labels to select which pods must come under a deployment. 
  selector:
    matchLabels:
      {{- include "qba.selectorLabels" . | nindent 6 }}
      # {{- with .Values.podLabels }}
      # {{- toYaml . | nindent 8 }}
      # {{- end }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      #These are labels attached specifically to pods. 
      labels:
        {{- include "qba.selectorLabels" . | nindent 6 }}
        # {{- with .Values.podLabels }}
        # {{- toYaml . | nindent 8 }}
        # {{- end }}
        
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: "{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .imagePullPolicy }}
        
        ports:
        {{- range .ports }}
          - name: {{ .name }}
            containerPort: {{ .containerPort }}
            protocol: {{ .protocol }}
        {{- end }}

        {{- if .env }}
        env:
        {{- range .env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
        {{- end }}
        {{- end }}

        {{- if .configMapRef }}
        envFrom:
          - configMapRef:
              name: {{ .configMapRef }}
        {{- end }}

        {{- if .resources }}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}

        {{- if .livenessProbe }}
        {{- with .livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}

        {{- if .readinessProbe }}
        {{- with .readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}

        {{- if .volumeMounts }}
        {{- with .volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}

        {{- if .volumes }}
        {{- with .volumes }}
        volumes:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}

      {{- end }}

      
