{{- $root := . }}

{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:  
    app.kubernetes.io/service-name: {{ .name }}
    {{- include "qba.selectorLabels" $root | nindent 4 }}
    {{- with $root.Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  type: {{ .type | default "ClusterIP" }}

  #Mandatory.
  selector:
    {{- include "qba.selectorLabels" $root | nindent 4 }}
    
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
---
{{- end }}
