#This is a customizable Helm chart template. It creates a configmap per container to make it easy to inject environment variables through ArgoCD.
#A single serviceaccount, role and role binding can be automatically creating by setting the respective create flags.
#Volume mounts, volumes and PVCs must be correctly specified. Requires the namespace to be pre-created to support the serviceaccount (if used).

#This is to override the chart name.
nameOverride: "" #Overrides the chart name.
fullnameOverride: "" #Overrides the fullname.
#Deployment
deployment:
  labels: {}
  annotations: {}
#Autoscaler.
replicaCount: 1 #Ignored when autoscaling is enabled.
autoscaling:
  enabled: true
  labels: {}
  annotations: {}
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75 #Is a percentage of container resource requests. 
  targetMemoryUtilizationPercentage: 75
  scaleUp:
    stabilizationWindowSeconds: 0 #How long to wait before scaling up after utilization has exceeded.
    policies:
      - type: Percent
        value: 50
        periodSeconds: 15 #Allow scaling up 50% of current replicas every 15 seconds.
  scaleDown:
    stabilizationWindowSeconds: 120 #How long to wait before scaling down after utilization has receded.
    policies:
      - type: Percent
        value: 50
        periodSeconds: 30 #Allow scaling down 50% of current replicas every 60 seconds.
#Update strategy.
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
#Custom labels to be added to all resources. Can query resources by these labels. 
#These are different from selector labels since they are not used for selection.
commonLabels:
  environment: qa
#Add custom metadata to pods. These are different from labels since they are not used for selection.
#They are for informational purposes.
podAnnotations: {}
#Image pull secrets.
imagePullSecrets:
  - name: aws-ecr
terminationGracePeriodSeconds: 30
#Security context for all containers in a pod except for initcontainers. This can be overriden on a container level.
podSecurityContext: {}
#Basic node selection rules.
nodeSelector: {}
# kubernetes.io/hostname: kubernetes-worker-1
#node-role.kubernetes.io/worker: ""
tolerations: []
#Advanced node selection rules.
affinity:
  #Node affinity rules to run pods on specific nodes.
  nodeAffinity: {}
  #This is a hard rule.
  # requiredDuringSchedulingIgnoredDuringExecution:
  #   nodeSelectorTerms:
  #     - matchExpressions:
  #         - key: kubernetes.io/hostname
  #           operator: In  #'In' requires a values while 'Exists' does not.
  #           values:
  #             - kubernetes-worker-1
  #             - kubernetes-worker-2
  #This is soft rule.
  # preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     preference:
  #       nodeSelectorTerm:
  #         matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - kubernetes-worker-1
  #               - kubernetes-worker-2
  #Pod antiaffinity rules to disperse pods of the same type across nodes.
  podAntiAffinity: {}
  #This is a hard rule.
  # requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #         - key: app.kubernetes.io/instance
  #           operator: In
  #           values:
  #             - crud-dev
  #         - key: app.kubernetes.io/name
  #           operator: In
  #           values:
  #             - crud
  #     topologyKey: "kubernetes.io/hostname"
  #This is soft rule.
  # preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       labelSelector:
  #         matchExpressions:
  #           - key: app.kubernetes.io/instance
  #             operator: In
  #             values:
  #               - crud-dev
  #           - key: app.kubernetes.io/name
  #             operator: In
  #             values:
  #               - crud
  #       topologyKey: "kubernetes.io/hostname"
#Init containers.
initContainers: []
# - name: init-logs
#   image: busybox:1.36
#   command: ["sh", "-c", "mkdir -p /var/log/nginx && chown -R 101:101 /var/log/nginx"]
#   volumeMounts:
#     - name: logs-app
#       mountPath: /var/log/nginx

#Containers.
containers:
  - name: backend
    repository: 104322896078.dkr.ecr.ap-southeast-1.amazonaws.com/s3-app/backend
    tag: 1.11.1-rc.1-HOTFIX-SNAPSHOT-20260729_063056-COMMITSHA_b95cf74b
    imagePullPolicy: IfNotPresent
    resources:
      requests: #Minimum guaranteed resources for the container to run. Also used by the HPA.
        cpu: "32m"
        memory: "128Mi"
      limits:
        cpu: "125m"
        memory: "256Mi"
    ports:
      - name: http
        containerPort: 3100
        protocol: TCP
    volumeMounts: []
    # - name: vault-token-app
    #   mountPath: "/etc/secrets"
    #   readOnly: true
    # - name: logs-app
    #   mountPath: "/var/log/nginx"
    #   readOnly: false
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 30
      periodSeconds: 15 # Check every 15s
      timeoutSeconds: 5 # Give the request 5s to respond
      failureThreshold: 3 # Restart after 3 consecutive failures
      successThreshold: 1 # Consider healthy after 1 success
    readinessProbe:
      httpGet:
        path: /api/health/live
        port: http
      initialDelaySeconds: 15
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1
    securityContext: []
    # runAsUser: 1000
    # runAsGroup: 3000
    # fsGroup: 2000
    secrets: []
    # - name: foo
    #   secretKeyRef:
    #     name: foo-secret
    #     key: password
    #     optional: false
    env: []
    # - name: ENV_VAR
    #   value: "value"
    envFromSecrets:
      - app-credentials #This secret would be created manually in the same namespace.
    command: []
    #   - "/bin/sh"
    #   - "-c"
    args: []
    #   - "while true; do curl http://localhost; done"
#Volumes.
volumes: []
# - name: vault-token-app
#   secret:
#     secretName: vault-token-app-secret
#     optional: false
# - name: logs-app             #This name will be used in the volumeMounts and the PVC claimName.
#   persistentVolumeClaim:
#     claimName: logs-app-crud

#PVCs. PVCs created by a Helm deployment will be deleted when the Helm release is deleted but will not delete for statefulsets unless explicitly stated.
pvc:
  create: false
  # list:
  #   - name: logs-app-crud
  #     size: 256Mi #1Gi
  #     accessModes:
  #       - ReadWriteOnce
  #     storageClassName: ""
  #     existingClaim: ""           #If set, chart will not create PVC
#An empty env list is required importing .envs from value files by ArgoCD.

env: {}
#Services.
service:
  - name: svc
    type: ClusterIP
    labels: {}
    annotations: {}
    ports:
      - name: web
        port: 80
        targetPort: 3300
      - name: api
        port: 8080
        targetPort: 3100
#Ingresses.
ingress:
  - name: ing
    enabled: true
    ingressClassName: nginx
    labels: {}
    annotations:
      #nginx.ingress.kubernetes.io/rewrite-target: /$1
      #nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      #nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    hosts:
      - host: qa.s3-app.com
        paths:
          - path: /
            pathType: Prefix
            service:
              name: svc
              port:
                number: 80
      - host: qa.api.s3-app.com
        paths:
          - path: /
            pathType: Prefix
            service:
              name: svc
              port:
                number: 8080
    tls: []
    # - hosts:
    #     - app.example.com
    #   secretName: app-tls
#Service accounts.
serviceAccount:
  create: true
  name: sa
  labels: {}
  annotations: {}
  #Prevents mounting a kubernetes API token at /var/run/secrets/kubernetes.io/serviceaccount/token in the container.
  #Therefore, even if RBAC permissions are accidentally granted, the application will not be able to access the Kubernetes API.
  automountServiceAccountToken: true
# - name: worker-sa
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/my-api-role

#Role.
role:
  create: true
  name: rl
  labels: {}
  annotations: {}
  rules:
    - apiGroups: [""]
      resources:
        - secrets
      verbs:
        - get
        - create
        - delete
        - update
        - patch
#Role binding.
roleBinding:
  create: true
  name: rb
  labels: {}
  annotations: {}
  subjects:
    - kind: ServiceAccount
      name: sa
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rl
#Cron job.
cronJob:
  enabled: true
  name: aws-ecr-secret-refresher
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  restartPolicy: OnFailure
  secretName: aws-ecr-credentials #This secret would be created manually in the same namespace.
  image:
    repository: amazon/aws-cli
    tag: latest
    pullPolicy: IfNotPresent
