{{- $root := . }}

{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ include "crud.fullname" $root }}
  labels:
  {{- include "crud.labels" $root | nindent 4 }}
  {{- with $root.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .type | default "ClusterIP" }}

  #Mandatory to target the correct pods.
  selector:
    {{- include "crud.selectorLabels" $root | nindent 4 }}
    
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
---
{{- end }}
