---
apiVersion: v1
kind: ConfigMap
metadata:
  name: back-end-config
data:
  RABBITMQ_HOST: qba-rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: ranul
  RABBITMQ_PASSWORD: ranul@123
  QUEUE_NAME: default_queue
  RANDOM_LENGTH: "10"
  PUBLISH_INTERVAL: "2000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_DEFAULT_USER: ranul
  RABBITMQ_DEFAULT_PASS: "ranul@123"