#This will install Loki in the monitoring namespace.

#Update the helm repository.
#helm repo add grafana https://grafana.github.io/helm-charts
#helm repo update

#Install.
# helm install loki grafana/loki \
#   --namespace monitoring \
#   --set grafana.enabled=false \
#   --set promtail.enabled=true
#   --set persistence.enabled=true \
#   --set persistence.size=1Gi

#Install with a custom values file.
#helm install loki grafana/loki -f loki.yaml --namespace monitoring  

#Add loki as a data source in grafana.
#http://loki:3100

#Distributed mode required a shared storage such as NFS or S3.
deploymentMode: SingleBinary

singleBinary:
  replicas: 1 #Set to 1 if singlebinary is used.

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1 #Set to 1 if singlebinary is used.
  resources:
    requests:
      cpu: 64m
      memory: 256Mi
    limits:
      memory: 1Gi
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "local-path"  #Set as nfs if distributed mode is used.
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    retention_period: 48h

#Not used if singlebinary is used.
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

#For memory caching if the query load is high.
memcached:
  enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 64m
    limits:
      memory: 4Gi
      cpu: 250m