#ArgoCD application for the dev environment.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-app-dev #This becomes the release name.
  namespace: argocd
spec:
  project: s3-app
  source:
    repoURL: git@github.com:Ranuldeepanayake/helm.git
    targetRevision: develop
    path: charts/s3-app
    helm:
      valueFiles:
        - ../../environments/s3-app/dev/values.yaml
        - ../../environments/s3-app/dev/env.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: s3-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=false
        - Validate=false
        - Replace=false
        - Force=false
        - ServerSideApply=false