selectorLabels:
  environment: dev

replicaCount: 1

containers:
  - name: back-end
    repository: public.ecr.aws/l4a5c1v5/qba/qba-back-end
    tag: 0.1.0-SNAPSHOT-20260101_175012-COMMITSHA_d1a48b3b
    imagePullPolicy: IfNotPresent
    ports:
      - name: http-api
        containerPort: 80
        protocol: TCP
    env: {}
    secrets: {}
    configMapRef: qba-back-end-config
    resources:
      requests:
        cpu: "125m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  - name: rabbitmq
    repository: rabbitmq
    tag: management
    imagePullPolicy: IfNotPresent
    ports:
      - name: http-management
        containerPort: 15672
        protocol: TCP
      - name: amqp
        containerPort: 5672
        protocol: TCP
    env: {}
    secrets: {}
    configMapRef: qba-rabbitmq-config
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "2"
        memory: "4Gi"

#Empty env field to append when merging value files by ArgoCD.
env: {}

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: aws-ecr

#Service.
service:
  - name: qba
    type: ClusterIP
    ports:
      - name: qba-front-end
        port: 80
        targetPort: 80
      - name: qba-back-end
        port: 8080
        targetPort: 8080
  - name: qba-rabbitmq
    type: ClusterIP
    ports:
      - name: qba-rabbitmq-management
        port: 15672
        targetPort: 15672
      - name: qba-rabbitmq-amqp
        port: 5672
        targetPort: 5672

#Ingress.
ingress:
  enabled: true
  className: nginx
  annotations:
  #nginx.ingress.kubernetes.io/rewrite-target: /$1
  #nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: qba.mydomain.com
      paths:
        - path: /(/|$)(.*)
          pathType: ImplementationSpecific
          service:
            name: qba
            port:
              number: 80
        - path: /backend(/|$)(.*)
          pathType: ImplementationSpecific
          service:
            name: qba
            port:
              number: 8080
    - host: qbarmq.mydomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: qba-rabbitmq
            port:
              number: 15672
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# This is to override the chart name.
nameOverride: ""

fullnameOverride: ""

podAnnotations: {}

podLabels:
  environment: dev

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
